services:
  frontend:
    build: ./frontend
    hostname: frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"

  backend:
    build: ./backend
    hostname: backend
    container_name: backend
    restart: always
    depends_on:
      - redis
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"

  redis:
    image: redis
    hostname: redis
    container_name: redis
    restart: always
    env_file:
      - .env
    ports:
      - "6379:6379"