services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5438:5432"
    volumes:
      - ./data/data:/var/lib/postgresql/data